<a href="https://colab.research.google.com/github/sunghyuncho992/python_programming/blob/main/11%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C_2024130310_%EC%A1%B0%EC%84%B1%ED%98%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [11]:
# Array fundamentals
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [5]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [6]:
a[:3]

array([10,  2,  3])

In [7]:
b = a[3:]
b

array([4, 5, 6])

In [8]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [16]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
a[1,3]

np.int64(8)

In [18]:
# Array attributes
a.ndim

2

In [22]:
a.shape

(3, 4)

In [23]:
len(a.shape) == a.ndim

True

In [25]:
a.size

12

In [26]:
import math
a.size == math.prod(a.shape)

True

In [27]:
a.dtype

dtype('int64')

In [28]:
# How to create a basic array

np.zeros(2)

array([0., 0.])

In [29]:
np.ones(2)

array([1., 1.])

In [33]:
np.empty(2)

array([1., 1.])

In [34]:
np.arange(4)

array([0, 1, 2, 3])

In [35]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [36]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [43]:
# Adding, removing, and sorting elements

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
# How do you know the shape and size of an array?

array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

array_example.ndim

3

In [47]:
array_example.size

24

In [48]:
array_example.shape

(3, 2, 4)

In [49]:
# Can you reshape an array?

a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [50]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [56]:
a = np.arange(6)
print(a)

b = a.reshape(3, 2)
print(b)

np.reshape(a, (1, 6), order='C')

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


array([[0, 1, 2, 3, 4, 5]])

In [57]:
# How to convert a 1D array into a 2D array (how to add a new axis to an array)

a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [58]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [59]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [60]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [61]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [62]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [63]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [65]:
#Indexing and slicing

data = np.array([1, 2, 3])

data[1]

np.int64(2)

In [66]:
data[0:2]

array([1, 2])

In [68]:
data[1:]

array([2, 3])

In [69]:
data[-2:]

array([2, 3])

In [72]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [73]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [74]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [75]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [76]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [78]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [79]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [80]:
print(a[b])

[1 2 3 4]


In [81]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [82]:
#How to create an array from existing data

a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [84]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [85]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [86]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [87]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [88]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [90]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0, :]
b1
b1[0] = 99
b1
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
b2 = a.copy()

In [92]:
#Basic array operations

data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [93]:
data - ones
data * data
data / data

array([1., 1.])

In [94]:
a = np.array([1, 2, 3, 4])

a.sum()

np.int64(10)

In [95]:
b = np.array([[1, 1], [2, 2]])

In [96]:
b.sum(axis=0)

array([3, 3])

In [97]:
b.sum(axis=1)

array([2, 4])

In [98]:
#Broadcasting

data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [100]:
#More useful array operations

data.max()

np.float64(2.0)

In [101]:
data.min()

np.float64(1.0)

In [102]:
data.sum()

np.float64(3.0)

In [104]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

a.sum()

np.float64(4.8595784)

In [105]:
a.min()

np.float64(0.05093587)

In [106]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [107]:
#Creating matrices

data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [108]:
data[0, 1]
data[1:3]
data[0:2, 0]

array([1, 3])

In [110]:
data.max()

np.int64(6)

In [111]:
data.min()

np.int64(1)

In [112]:
data.sum()

np.int64(21)

In [114]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [116]:
data.max(axis=0)

array([5, 6])

In [117]:
data.max(axis=1)

array([2, 5, 6])

In [118]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [119]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [120]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [123]:
np.ones(3)

array([1., 1., 1.])

In [124]:
np.zeros(3)

array([0., 0., 0.])

In [128]:
rng = np.random.default_rng()
rng.random(3)

array([0.84093363, 0.86640285, 0.62683495])

In [129]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [130]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [131]:
rng.random((3,2))

array([[0.76410251, 0.9150139 ],
       [0.33432531, 0.72744541],
       [0.07297447, 0.8546397 ]])

In [133]:
#Generating random numbers
rng.integers(5, size=(2, 4))

array([[0, 4, 2, 1],
       [1, 4, 3, 4]])

In [135]:
#how to get unique items and counts
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [136]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [137]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [138]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [139]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


In [140]:
#Transposing and reshaping a matrix

data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [142]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [143]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [144]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [147]:
#How to reverse an array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [148]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [149]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [150]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [151]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [152]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [153]:
#Reshaping and flattening multidimensional arrays

x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [155]:
a1 = x.flatten()
a1[0] = 99
print(x)
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [156]:
a2 = x.ravel()
a2[0] = 98
print(x)
print(a2)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
